### ISSUE TITLE
Notifier-api start delays by 60s (Rabbit configuration)

### ISSUE THREAD

**Issue by mikron** [sflpro/notifier#108]
The error from application log
```
ERROR 6960 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Consumer failed to start in 60000 milliseconds; does the task executor have enough threads to support the container concurrency?
```
This [PR ](https://github.com/spring-projects/spring-amqp/pull/925)on [spring-amqp](https://github.com/spring-projects/spring-amqp) fixes the issue.

**Comment by dnavre** [comment]
Fixed in #112. will be released in 1.9.0
