### ISSUE TITLE
Fix ignored integration tests

### ISSUE THREAD

**Issue by rubvardanyan** [sflpro/notifier#17]
A number of integration/unit tests are ignored for long forgotten reasons. Each one has to be evaluated separately and either fixed or deleted.

----
Description added by Yervand Aghabayan

**Comment by dnavre** [comment]
Twillio integration tests are now enabled and working via Twillio sandbox.

@Syuziko is now looking into doing something similar with Amazon SNS.

**Comment by mkrtchyanh** [comment]
I enabled all the ignored tests, but only for AmazonSnsApiCommunicatorIntegrationTest
we need to provide accesskey,secretkey when running them, otherwise, the test cases will not be executed.

**Comment by dnavre** [comment]
I'm closing this as nearly all the tests are re-enabled. Specifically for Amazon SNS tests, I created a new issue: https://github.com/sflpro/notifier/issues/94
