### ISSUE TITLE
Inconsistent api client library resource urls.

### ISSUE THREAD

**Issue by danielyan11vazgen** [sflpro/notifier#91]
EmailNotificationResourceClientImpl,PushNotificationResourceClientImpl,SmsNotificationResourceClientImpl uses different urls when configuring rest client in case when context path set to :
server.servlet.context-path=/*
For example:
EmailNotificationResourceClientImpl => "notification/email/create"
SmsNotificationResourceClientImpl => "rest/notification/sms/create". Also

**Comment by dnavre** [comment]
This is fixed in version 0.17.0
